// Generated by scripts/generate-local-result-readiness-manifest.mjs.
// Do not edit manually; regenerate after changing fixtures/synthetic/*.result.json.

export type LocalResultReadiness = {
  resultRows: number;
  plainEnglishRows: number;
  plainEnglishReady: boolean;
  appendixProbabilityCount: number;
  appendixProbabilityReady: boolean;
};

export const localResultReadinessBySlug: Record<string, LocalResultReadiness> = {
  "age-strength": {
    "resultRows": 8,
    "plainEnglishRows": 8,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "ai-reports": {
    "resultRows": 11,
    "plainEnglishRows": 11,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "am-i-related-albert-einstein-dna": {
    "resultRows": 7,
    "plainEnglishRows": 7,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "ancestry-explorer": {
    "resultRows": 10,
    "plainEnglishRows": 10,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "ancestry-genealogy-heritage": {
    "resultRows": 7,
    "plainEnglishRows": 7,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "anesthesiologist-summary": {
    "resultRows": 6,
    "plainEnglishRows": 6,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "apoe4-test-brain-health-genetic-analysis": {
    "resultRows": 5,
    "plainEnglishRows": 5,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "arthritis-prevention-dna-report": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "athletic-performance": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "autoimmune-disorders": {
    "resultRows": 8,
    "plainEnglishRows": 8,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "blood-dna-analysis-report": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "blood-glucose-insight": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "blood-type-dna-analysis-genetic-report": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "brain-health": {
    "resultRows": 16,
    "plainEnglishRows": 16,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "brain-mental-health-mood-dna-report": {
    "resultRows": 16,
    "plainEnglishRows": 16,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "breast-cancer-risk-prevention": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "cancer-prs": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "cancer-risk": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "cannabis-dna-health-report-genetic-analysis": {
    "resultRows": 12,
    "plainEnglishRows": 12,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "cardiometabolic-health-prs": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "cardiovascular-dna-analysis-heart-health-genetic-report": {
    "resultRows": 5,
    "plainEnglishRows": 5,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "cardiovascular-health": {
    "resultRows": 8,
    "plainEnglishRows": 8,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "carrier-screening": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "carrier-status-rare-disease-genetic-report": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "charcot-marie-tooth": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "chronic-fatigue-dna-health-report": {
    "resultRows": 17,
    "plainEnglishRows": 17,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "chronic-pain-dna-report": {
    "resultRows": 16,
    "plainEnglishRows": 16,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "clinical-annotator-variants": {
    "resultRows": 9,
    "plainEnglishRows": 9,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "colon-cancer": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "complete-genome-analysis": {
    "resultRows": 13,
    "plainEnglishRows": 13,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "comprehensive-health-screen-wgs-bundle": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "connective-tissue-disorders-and-eds": {
    "resultRows": 2,
    "plainEnglishRows": 2,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "convert-rsids-coordinates": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "detox-pathway": {
    "resultRows": 17,
    "plainEnglishRows": 17,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "developmental-disorders": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "digestive-disorders-gut-health": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "dna-ancestry-genetic-genealogy-report": {
    "resultRows": 11,
    "plainEnglishRows": 11,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "dna-diet-personalized-weight-loss-app": {
    "resultRows": 2,
    "plainEnglishRows": 2,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "dysautonomia": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "ehlers-danlos-syndrome": {
    "resultRows": 2,
    "plainEnglishRows": 2,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "empower": {
    "resultRows": 18,
    "plainEnglishRows": 18,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "endocrine-health": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "endometrial-cancer-risk-prevention": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "eve-premium-dna-genome-data-bioinformatics-pipelines": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "expedited-advanced-health-screen-wgs-bundle": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "female-sexual-reproductive-health-dna-report": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "fitness-dna-test-report": {
    "resultRows": 15,
    "plainEnglishRows": 15,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "fitness-trainer-summary": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "food-sensitivity": {
    "resultRows": 10,
    "plainEnglishRows": 10,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "gene-form-dna-personalized-fitness-app": {
    "resultRows": 15,
    "plainEnglishRows": 15,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genetic-counseling": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genetic-detoxification-genevironment": {
    "resultRows": 2,
    "plainEnglishRows": 2,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genetic-test-for-iq-cognitive-function": {
    "resultRows": 10,
    "plainEnglishRows": 10,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "genetic-test-predict-physical-appearance": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genetic-test-traits": {
    "resultRows": 21,
    "plainEnglishRows": 21,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genetic-testing-disease-risk": {
    "resultRows": 11,
    "plainEnglishRows": 11,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "geneticist-summary": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genome-explorer-dna-data-search": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genome-overview": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "genome-short-read-mapper": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "growth-bone-health": {
    "resultRows": 8,
    "plainEnglishRows": 8,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "gut-health": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "hair-loss-balding-dna-test": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "health-scan": {
    "resultRows": 12,
    "plainEnglishRows": 12,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "healthcare-pro-genetic-report": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "healthcare-professional-summary": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "healthy-heart-dna-analysis-genetic-report": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "healthy-nutrition-dna-analysis-app": {
    "resultRows": 17,
    "plainEnglishRows": 17,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "healthy-weight": {
    "resultRows": 13,
    "plainEnglishRows": 13,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "hearing-auditory-genetics": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "heart-health-genetic-guide": {
    "resultRows": 17,
    "plainEnglishRows": 17,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "histamine": {
    "resultRows": 10,
    "plainEnglishRows": 10,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "hormone-health-dna-report": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "immune-system-health": {
    "resultRows": 13,
    "plainEnglishRows": 13,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "imputation-analysis": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "infectious-disease-specialist-summary": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "inflammation-dna-analysis-wellness-genetic-report": {
    "resultRows": 13,
    "plainEnglishRows": 13,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "inflammation": {
    "resultRows": 5,
    "plainEnglishRows": 5,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "insights-food-response-and-nutrient-sensitivity": {
    "resultRows": 24,
    "plainEnglishRows": 24,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "kidney-cancer": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "kidneys-and-urinary-tract-dna-health-report": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "longevity-dna-test-wellness-report": {
    "resultRows": 6,
    "plainEnglishRows": 6,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "lupus": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "male-sexual-and-reproductive-health-dna-report": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "malignant-hyperthermia-genetic-testing": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "map-my-genes-archaeology-edition": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "map-my-genes-dna-ancestry-analysis": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "marfan-syndrome": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "medication-drug-response": {
    "resultRows": 5,
    "plainEnglishRows": 5,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "medication-pharmacogenomics-dna-report": {
    "resultRows": 24,
    "plainEnglishRows": 24,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "medications-pgx-complete-dna-guide": {
    "resultRows": 6,
    "plainEnglishRows": 6,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "melanoma-skin-cancer-dna-test-analysis": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "mental-health-genetic-guide": {
    "resultRows": 15,
    "plainEnglishRows": 15,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "metabolic-health-dna-report": {
    "resultRows": 24,
    "plainEnglishRows": 24,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "methylation-pathway": {
    "resultRows": 8,
    "plainEnglishRows": 8,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "mitchell-syndrome": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "mitochondrial-ancestry": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "mosaic-biodata": {
    "resultRows": 19,
    "plainEnglishRows": 19,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "mthfr-dna-wellness-report": {
    "resultRows": 6,
    "plainEnglishRows": 6,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "musculoskeletal-dna-report": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "musculoskeletal-health": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "my-heart-health": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "my-personality-traits": {
    "resultRows": 12,
    "plainEnglishRows": 12,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "naturopath-summary": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "neurological-health": {
    "resultRows": 16,
    "plainEnglishRows": 16,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "next-gen-disease-screen": {
    "resultRows": 12,
    "plainEnglishRows": 12,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "nourish": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "nutrigenomics-dna-nutrition-guidance": {
    "resultRows": 2,
    "plainEnglishRows": 2,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "nutritional-metabolic-health": {
    "resultRows": 24,
    "plainEnglishRows": 24,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "nutritionist-summary": {
    "resultRows": 24,
    "plainEnglishRows": 24,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "oncology-genetic-guide": {
    "resultRows": 15,
    "plainEnglishRows": 15,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "oral": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "ovarian-cancer-risk-prevention": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "ozempic-glp-1-agonists-genetic-report": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "pancreatic-cancer": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "parkinsons-disease": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "pediatric-health": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "personalized-vitamins-and-supplements": {
    "resultRows": 13,
    "plainEnglishRows": 13,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "pharmacist-summary": {
    "resultRows": 10,
    "plainEnglishRows": 10,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "pheochromocytoma-and-paraganglioma": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "preconception-pregnancy-planning": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "prevent-breast-cancer-dna-analysis-report": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "prevent-sudden-death": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "promethease": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "prostate-cancer-risk-prevention": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "radiation-uv-sensitivity": {
    "resultRows": 2,
    "plainEnglishRows": 2,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "reproductive-hormonal-health": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "respiratory-health-dna-report": {
    "resultRows": 16,
    "plainEnglishRows": 16,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "respiratory-health": {
    "resultRows": 14,
    "plainEnglishRows": 14,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "rheumatologist-summary": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "rundna": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "santa-and-me-app-dna-comparison": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "sequencing-depth-and-coverage": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "skin-and-beauty-dna-report": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "skin-cancer": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "skin-genes-dna-analysis-app": {
    "resultRows": 9,
    "plainEnglishRows": 9,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "skin-health": {
    "resultRows": 2,
    "plainEnglishRows": 2,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "sleep-dna-analysis-wellness-report": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "strategene": {
    "resultRows": 8,
    "plainEnglishRows": 8,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "surgeon-summary": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "tbg-total-wellness": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "thrive": {
    "resultRows": 13,
    "plainEnglishRows": 13,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "thyroid-cancer": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "toxin-sensitivity": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "ultra-rapid-professional-health-screen-wgs-bundle": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "variant-discovery-bioinformatics-secondary-analysis": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "variant-effect-predictor": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "vision": {
    "resultRows": 4,
    "plainEnglishRows": 4,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "vitamins-dna-analysis-genetic-report": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "wellness-and-longevity": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "wellness-genetic-guide": {
    "resultRows": 22,
    "plainEnglishRows": 22,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 1,
    "appendixProbabilityReady": true
  },
  "whole-genome-sequencing-30x": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "will-aspirin-help": {
    "resultRows": 3,
    "plainEnglishRows": 3,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  },
  "world-ancestry-report": {
    "resultRows": 16,
    "plainEnglishRows": 16,
    "plainEnglishReady": true,
    "appendixProbabilityCount": 0,
    "appendixProbabilityReady": true
  }
};
